In [1]:
import numpy as np
import time

In [2]:
arr=np.array([1,2,3,4,5])
print(arr,type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [3]:
#time taken to run the program
size=1_000_00_00

py_list=list(range(size))
start=time.time()
sq_list=[x**2 for x in py_list]
end=time.time()
print(f"Python list time ={end-start} seconds")


np_arr=np.array(py_list)
start=time.time()
sq_array=np_arr**2
end=time.time()
print(f"numpy array time ={end-start} seconds")

Python list time =2.5434203147888184 seconds
numpy array time =0.06209063529968262 seconds


In [4]:
#size taken by them
import sys

print(f"Python lists size ={sys.getsizeof(py_list)*len(py_list)} bytes")
print(f"Numpy array size ={np_arr.nbytes} bytes")

Python lists size =800000560000000 bytes
Numpy array size =80000000 bytes


In [5]:
#create_from lists
arr=np.array([1,2,3,4,5])
print(arr,type(arr),arr.dtype,arr.shape)

arr2=np.array([1,2,3,4,5,"prime"])
print(arr2,type(arr2),arr2.dtype,arr2.shape) 

arr2D=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr2D,arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (6,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)


In [6]:
arr1=np.zeros((2,3),dtype="int64")
print(arr1,arr1.shape)

arr2=np.ones((5,))
print(arr2,arr2.shape)

arr3=np.full((3,4),100)
print(arr3,arr3.shape)

arr4=np.eye(3)
print(arr4,arr4.shape)

arr5=np.arange(0,11,2)
print(arr5,arr5.shape)

arr6=np.linspace(1,100,3)
print(arr6,arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1. 1. 1. 1. 1.] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  1.   50.5 100. ] (3,)


In [7]:
#properties
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)
      
float_arr=arr.astype(np.float64)
print(float_arr,float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [8]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

reshaped=arr.reshape((3,2))
print(reshaped,reshaped.shape)

flattend=arr.flatten()
print(flattend,flattend.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [9]:
#indexing
arr=np.array([1,2,3,4,5])
arr1=np.array([[1,2,3],[4,5,6]])

print(arr[0])
print(arr1[1][2])

#fancy indexing
arr3=np.array([1,2,3,4,5])
idx=[0,1,3]
print(arr[idx])

#boolean indexing
arr4=np.array([1,2,3,4,5])
print(arr4[arr>3])
print(arr4[arr%2==0])

#slicing
arr5=np.array([1,2,3,4,5])
print(arr5[1:4])
print(arr5[::])

1
6
[1 2 4]
[4 5]
[2 4]
[2 3 4]
[1 2 3 4 5]


In [10]:
#copy vs view
nums=[1,2,3,4,5]
sub_list=nums[1:3]
print(sub_list)
sub_list[0]=200
print(sub_list)
print(nums)
arr=np.array([1,2,3,4,5])

[2, 3]
[200, 3]
[1, 2, 3, 4, 5]


In [11]:
#copy vs view
arr=np.array([1,2,3,4,5])
sub_arr=arr[1:3].copy()
print(sub_arr)

sub_arr[0]=200
    
print(sub_arr)
print(arr)

[2 3]
[200   3]
[1 2 3 4 5]


In [12]:
#data types

arr=np.array([1,2,3,4,5])
print(arr,arr.dtype)

[1 2 3 4 5] int64


In [13]:
#data types

arr=np.array([1,2,3.14,4,5])
print(arr,arr.dtype)

[1.   2.   3.14 4.   5.  ] float64


In [14]:
#data types

arr=np.array([1,2,3,4,5,"prime"])
print(arr,arr.dtype)

['1' '2' '3' '4' '5' 'prime'] <U21


In [15]:
#data types

arr=np.array([3+5j])
print(arr,arr.dtype)

[3.+5.j] complex128


In [16]:
#data types

arr1=np.array([3+5j])
arr2=np.array([2+3j])
print(arr1+arr2)
print(arr1-arr2)

[5.+8.j]
[1.+2.j]


In [17]:
arr=np.array(["prime",{1,2,3},3.14])
print(arr,arr.dtype)

['prime' {1, 2, 3} 3.14] object


In [42]:
#multidimensional arrays

arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

print(np.sum(arr2D))

sum_of_cols=np.sum(arr2D,axis=0)
print(sum_of_cols)

sum_of_rows=np.sum(arr2D,axis=1)
print(sum_of_rows)

print(arr2D[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [45]:
#3D array

arr3D=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]]) #2x3x2
print(arr3D,arr3D.shape)
#indexing
print(arr3D[1,1,0])

#slicing
print(arr3D[:,0,:])
print(arr3D[:,:,0])


arr3D[:,0,:]=99
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
9
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [48]:
#vectorization

arr=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print(arr**2)
print(arr+10)
print(arr+arr2)

[ 1  4  9 16 25]
[11 12 13 14 15]
[ 7  9 11 13 15]


In [55]:
#brodcasting
arr=np.array([1,2,3,4,5])
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr+5)
print(arr.shape,arr2.shape)
print(arr+arr2)

[ 6  7  8  9 10]
(5,) (2, 5)
[[ 2  4  6  8 10]
 [ 7  9 11 13 15]]


In [60]:
#normalization

arr=np.array([[1,2],[3,4]])
mean=np.mean(arr)
std_dev=np.std(arr)

normalized_arr=(arr-mean)/std_dev
print(normalized_arr)

print(mean)
print(std_dev)
print(np.sqrt(5/4))

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895
1.118033988749895


In [63]:
#mathematical functions

#aggregration function

arr=np.array([1,2,3,4,5])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))

15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0


In [69]:
#power function

arr=np.array([1,2,3,4,5])
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [73]:
#log
arr=np.array([1,2,3,4,5])

print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [82]:
#rounding

arr=np.array([1,2,3,4,5,7,8,2,2,-3,-4,-7])

print(np.round(3.89))
print(np.ceil(3.89))
print(np.floor(3.89))
print(np.trunc(3.89))

print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))

4.0
4.0
3.0
3.0
[-7 -4 -3  1  2  3  4  5  7  8]
[-7 -4 -3  1  2  2  2  3  4  5  7  8]
[1 2 3 4 5 7 8 2 2 3 4 7]


##### 